#
# This file is part of the PocketSVG package.
#
# Copyright (c) Ponderwell, Ariel Elkin, Fjölnir Ásgeirsson, and Contributors
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

name: CI

on:
  push:
    branches: [master]
    tags:
      - '*' # run on every tag
  pull_request:

jobs:
  primary:
    name: Primary
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.2.app

      - name: Build demos
        run: sh ci/build_demos.sh

      - name: Run unit tests
        run: sh ci/test.sh

  cocoapods:
    name: Cocoapods
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Lint Podspec
        run: pod lib lint

  spm:
    name: Swift Package Manager
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Swift Build
        run: swift build

  xcframework:
    name: XCFramework
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Build XCFramework
        run: ci/build_xcframework.sh

      - name: Create release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') # only if tag is pushed
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          TAG_NAME=${GITHUB_REF#refs/*/}

          gh release create $TAG_NAME --notes ""

          zip -r9 PocketSVG.xcframework.zip derived_data/xcframework/PocketSVG.xcframework

          gh release upload $TAG_NAME PocketSVG.xcframework.zip   
